name: Update Greeting Banner

on:
  # Esegue l'azione ogni ora
  schedule:
    - cron: "0 * * * *"
  # Permette di eseguire l'azione manualmente dalla tab "Actions"
  workflow_dispatch:

jobs:
  update-greeting:
    runs-on: ubuntu-latest
    steps:
      # 1. Fa il checkout del tuo repository per accedere ai file
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Sceglie il banner corretto in base all'ora
      - name: Update greeting based on time
        # Imposta la timezone italiana e controlla l'ora corrente
        run: |
          HOUR=$(TZ='Europe/Rome' date +'%H')
          GREETING_SVG=""

          if (( HOUR >= 7 && HOUR < 14 )); then
            GREETING_SVG="assets/buongiorno.svg"
          elif (( HOUR >= 14 && HOUR < 19 )); then
            GREETING_SVG="assets/buonpomeriggio.svg"
          else
            GREETING_SVG="assets/buonasera.svg"
          fi
          
          echo "Selected greeting: $GREETING_SVG"
          # Copia il file SVG scelto e lo rinomina in "greeting.svg"
          cp $GREETING_SVG greeting.svg

      # 3. Fa il commit del file aggiornato nel repository
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update greeting banner"
          file_pattern: greeting.svg
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"